project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: logo.png
  site-url: https://papadakievi.github.io/
  description: "Beyond the mathematics of the moment"

  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - projects.qmd
      - bibliography.qmd
      #- href: blog.qmd
      #  text: blog
     # - href: resume.pdf
     #   text: CV
     #   target: _blank
      - text: Get in touch!
        menu:
         - icon: instagram
           text: instagram
           href: https://www.instagram.com/academic_scribbles/
           target: _blank
         - icon: linkedin
           text: linkedin
           href: https://www.linkedin.com/in/evi-papadaki/
           target: _blank
         - icon: envelope
           text: email
           href: mailto:pp949@bath.ac.uk
    logo: title.png
    logo-alt: "beyond the mathematics of the moment by Evi Papadaki" 
    logo-href: index.qmd
    comments:
      giscus:
        repo: PapadakiEvi/papadakievi.github.io
  page-footer: 
      background: white
      left: © Evi Papadaki 2024

format:
  html:
    theme: 
     - styles.css
    mainfont: Nunito
    toc: true
    toc-depth: 2

editor: visual

