---
title: "Bibliography"
---

# Journal articles

::: bib-entry
Smith, T., & Papadaki, E. (in press) What role does skill centre based consultancy serve in mathematics and statistics teaching communities of practice?. *MSOR Connections*.
:::

# Doctoral thesis

::: bib-entry
Papadaki, E. (2023). Beyond the Mathematics of the Moment: Exploring Teacher Discourse at the Mathematical Horizon. \[Doctoral thesis, University of East Anglia\]. <https://ueaeprints.uea.ac.uk/id/eprint/93504/1/2023-Papadaki.P-PhD_Final_Thesis.pdf>
:::

# Papers in peer-reviewed conference proceedings

::: bib-entry
Papastathi, C., Kanellos, I., Papadaki, E., Biza, I., & Nardi, E. (2022). Πάρε θεση! Η μαθηματική απόδειξη ως εργαλείο τεκμηρίωσης στην τάξη \[Make up your mind! The mathematical proof as an argumentation instrument in the class\]. *Proceedings of Nineth Conference of the Greek Association of Research in Mathematics Education (Εν.Ε.Δι.Μ. 9)*, Εν.Ε.Δι.Μ.
:::

::: bib-entry
Biza, I., Nardi, E., Argyris, D., Kalikakis, D., Kanellos, I., Kotarinou, P., Koukoulakis, C., Mpalabanidou, Z., Papadaki, E., & Stylianidou, A. (2022). Μοντέλα επιμόρφωσης για την ανατροφοδότηση από την έρευνα στη διδακτική πράξη της διδασκαλίας των μαθηματικών και αντίστροφα \[Professional development models based on the reciprocal feedback between research and mathematics teaching practice\]. *Proceedings of Nineth Conference of the Greek Association of Research in Mathematics Education (Εν.Ε.Δι.Μ. 9)*, Εν.Ε.Δι.Μ.
:::

::: bib-entry
Papadaki, E. & Biza, I. (2022). Teaching beyond the mathematics of the moment, *Proceedings of the Twelfth Congress of the European Society for Research in Mathematics Education* (CERME 12). <https://hal.archives-ouvertes.fr/hal-03745470>
:::

::: bib-entry
Papadaki, E. (2021). Routines at the horizon: when and how a teacher can go beyond the mathematics of the moment. In Inprasitha, M., Changsri, N., Boonsena, N. (Eds.), *Proceedings of the 44th Conference of the International Group for the Psychology of Mathematics Education* (Vol.1) (p. 169). PME. <https://pme44.kku.ac.th/home/uploads/volumn/pme44_vol1.pdf>
:::

::: bib-entry
Papadaki, E. & Kourouniotis, C. (2018). Tasks for enriching the understanding of the concept of linear span. *Proceedings of the Second Conference of the International Network for Didactic Research in University Mathematics* (INDRUM2018, 5-7 April 2018), 275-284. <https://hal.archives-ouvertes.fr/hal-01849948/document>.
:::

::: bib-entry
Papadaki, E. & Kourouniotis, C. (2017). Η έννοια της γραμμικής θήκης μέσα από τα μάτια ενός πρωτοετή φοιτητή μαθηματικών \[The notion of linear span through the eyes of a first year mathematics student\]. *Proceedings of Seventh Conference of the Greek Association of Research in Mathematics Education (Εν.Ε.Δι.Μ. 7)*, Εν.Ε.Δι.Μ.
:::

::: bib-entry
Kourouniotis, C. & Papadaki, E. (2017). Η εισαγωγή της έννοιας του διανύσματος \[Introducing the concept of vectors\]. Poster session presented at *Seventh Conference of the Greek Association of Research in Mathematics Education* (Εν.Ε.Δι.Μ. 7), Εν.Ε.Δι.Μ.
:::

# Papers in conference proceedings (other)

::: bib-entry
Nardi, E., Biza, I., Moustapha-Corrêa, B., Papadaki, E., & Thoma, A. (2021). From student scribbles to institutional script: Towards a commognitive research and reform programme for university mathematics education. In R. Marks (Ed.), *Proceedings of the British Society for Research into Learning Mathematics,* 41 (1). British Society for Research into Learning Mathematics. <https://bsrlm.org.uk/publications/proceedings-of-day-conference/ip41-1/>
:::

::: bib-entry
Papadaki, E. & Biza, I. (2020). Conceptualising the Discourse at the Mathematical Horizon: Looking at one teacher’s actions “beyond the mathematics of the moment”. Proceedings of the British Society for Research into Learning *Mathematics*, 40 (1). <https://bsrlm.org.uk/wp-content/uploads/2020/05/BSRLM-CP-40-1-12.pdf>
:::

::: bib-entry
Papadaki, E. (2019). Mapping out different discourses of mathematical horizon. *Proceedings of the British Society for Research into Learning Mathematics*, 39 (1). <https://bsrlm.org.uk/wp-content/uploads/2019/07/BSRLM-CP-39-1-07.pdf>
:::

# Master dissertation

::: bib-entry
Papadaki, E. (2017). Design of tasks for the understanding of the concept of Linear Span. \[Master Dissertation, University of Crete\]. <https://elocus.lib.uoc.gr/dlib/6/b/a/metadata-dlib-1512027006-378155-4203.tkl>
:::
